### ISSUE TITLE
Dynamic Ja3 hash?

### ISSUE THREAD

**Issue by doroved** [picoHz/pawprint#2]
Hi. Why in chrome the Ja3 hash changes almost after every page reload, but in Safari it is always the same?

**Comment by doroved** [comment]
Could you tell me how to simulate browser TLS in reqwest library when sending https requests?
Or if not through reqwest, maybe you know another way?)

**Comment by picoHz** [comment]
> Why in chrome the Ja3 hash changes almost after every page reload, but in Safari it is always the same?

Chrome shuffles TLS extension list for every new connection. This 'TLS ClientHello permutation' generates randomized JA3 hashes.

[A first look at Chrome's TLS ClientHello permutation in the wild | Fastly](https://www.fastly.com/blog/a-first-look-at-chromes-tls-clienthello-permutation-in-the-wild)

> Could you tell me how to simulate browser TLS in reqwest library when sending https requests?
> Or if not through reqwest, maybe you know another way?)

It is difficult to directly spoof TLS in Rust because most HTTP clients rely on rustls or native-tls, which offer limited customization options for the TLS handshake. However, there are several tools and libraries available in other languages. You can use these tools via FFI / IPC or use them as an HTTPS proxy with reqwest.

https://github.com/lwthiker/curl-impersonate
https://github.com/Danny-Dasilva/CycleTLS
https://github.com/refraction-networking/utls

**Comment by doroved** [comment]
> It is difficult to directly spoof TLS in Rust because most HTTP clients rely on rustls or native-tls, which offer limited customization options for the TLS handshake.

Thank you for your reply.
I found this option, it worked for me, apparently the easiest option is to use BoringSSL
https://github.com/gssvv/rust-boring-ssl-client
Maybe you'll be interested and can adapt this elegantly for reqwest)

There is also this option, but I haven't tried it as it looks outdated
https://github.com/4JX/reqwest-impersonate

**Comment by picoHz** [comment]
I overlooked those libraries. 😅  Thanks for sharing.
